name: link-check
on:
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links (basic)
        run: |
          echo "Placeholder for a link checker (optional)."
